// The content of this file was generated by IBM Cloud
// No not modify it as it might get overridden

var IBMCloudEnv = require('ibm-cloud-env');
var serviceManager = require('./service-manager');
const log4js = require('log4js');
log4js.configure({
      appenders: { console: { type: 'console' } },
      categories: { default: { appenders: [ 'console' ], level: 'info' } }
  });
  
const logger = log4js.getLogger('createCustappDB');
logger.level = process.env.LOG_LEVEL || 'info' ;
IBMCloudEnv.init();

module.exports = function(app){
      require('./service-pgdb-cust').init(app, serviceManager);
      require('./service-pgdb-acnt').init(app, serviceManager);
      require('./service-pgdb-cards').init(app, serviceManager);

      require('./service-couchdb').init(app, serviceManager);
      const CustappSrvc =  require( './service-couchdb-crt');
      const tdbs = new CustappSrvc();
      tdbs.createCustappDB( function( err, dbres){
          if (err) {
                console.log(err.message);
          } else {
                console.log( JSON.stringify(dbres) )
          }
      });


};